### PR TITLE
Exposed --nadir_weight

### PR DESCRIPTION
**Pull request by pierotofy**
Allows a user to set the weight used in the nadir view data cost calculation.

### CODE REVIEW

**Comment by namibj** [comment]
If `OUTLIER_REMOVAL_NONE` is active, you should be able to skip `get_face_info` completely once you decide to go vertical.

Also, do you have anything to show for how `--nadir` improves the result? I would like to know whether to attempt to support it in my attempt at a GPU texrecon.

**Comment by pierotofy** [comment]
Here's an example: image

image

And another: image

**Comment by namibj** [comment]
Thanks, that's convincing. I assume it's because side views are much more sensitive to imperfections in the locations of mesh edges, and thus tend to transfer these artifacts into the final result.
I hope to be able to include support for this in the GPU version. It seems warranted.

Did you ever try to get these changes merged upstream?

It might be warranted to tune how mapMAP decides between using a single view for both the roof and the side, vs. using a side view for the side and a nadir view for the roof, even if that means not having the same view on the adjacent faces. That might be useful for a more robust configuration, which won't need that much manual tuning of `--nadir_weight`.

**Comment by pierotofy** [comment]
Haven't proposed them upstream, since I thought the use case is pretty specific to aerial images, but somebody could try to open a PR or ask nmoehrle if there's interest.

**Comment by namibj** [comment]
I will work on it later when I merge my remaining changes. It might take
couple weeks, but it's no rush.

**Pull request merged**
